### ISSUE TITLE
Database </database> is not complete or not indexed.

### ISSUE THREAD

**Issue by volcanihpc** [xinehc/melon#4]
Hello, 

I'm getting the error above using the GTDB database from [here](https://zenodo.org/records/12571554).
It was indexed according the instructions in the main page, I have these files inside the database folder:
` prot.fa`, `nucl.*.fa` and `metadata.tsv`

The command I'm running is:
`melon T2-C1_filt500.fasta --db /database -o melon
`

**Comment by xinehc** [comment]
Hi,

After indexing you should have exactly 16 `*.mmi` and 1 `*.dmnd` files in the database folder, otherwise the database is considered incomplete.

Please note the following code will index files in `./database` not `/database`. If you save the database under `/` then you need to move to the path for indexing.

```bash
cpu_count=$(python -c 'import os; print(os.cpu_count())')

diamond makedb --in database/prot.fa --db database/prot --quiet
ls database/nucl.*.fa | sort | xargs -P $cpu_count -I {} bash -c '
    filename=${1%.fa*};
    filename=${filename##*/};
    minimap2 -x map-ont -d database/$filename.mmi ${1} 2> /dev/null;
    echo "Indexed <database/$filename.fa>.";' - {}
```

**Comment by volcanihpc** [comment]
> After indexing you should have exactly 16 *.mmi and 1 *.dmnd files in the database folder, otherwise the database is considered incomplete.

Thanks!, I was missing the `*.mmi` files, turns out `minimap2` wasn't installed in my conda environment.

**Comment by volcanihpc** [comment]
> After indexing you should have exactly 16 *.mmi and 1 *.dmnd files in the database folder, otherwise the database is considered incomplete.

Thanks!, I was missing the `*.mmi` files, turns out `minimap2` wasn't installed in my conda environment.

**Comment by cliffbueno** [comment]
When I tried the default indexing code it was not creating .mmi files for the bacteria files. I edited this part of the code a bit as follows and it worked.

ls database/nucl.*.fa | sort | \
  xargs -P $cpu_count -I {} bash -c '
    infile="$1"
    filename=$(basename "${infile%.fa}")
    minimap2 -x map-ont -d "database/${filename}.mmi" "$infile"
  ' _ {}
